apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
  labels:
    app: supermario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario-deployment
  template:
    metadata:
      labels:
        app: supermario-deployment
    spec:
      containers:
      - name: supermario
        image: 34.60.163.6:8082/mario-nexus:latest
        ports:
        - containerPort: 8080