version: '2'

services:
  web:
    container_name: simplePythonFlask
    image: simple-python-flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - 'mariadb'

  web_initiate_db:
    container_name: simple-python-flask_init_db
    image: simple-python-flask
    entrypoint: ["python3","create_db.py"]
    depends_on:
    - 'mariadb'

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123qwe"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
        interval: 30s
        timeout: 20s
        retries: 10

  selenium:
    container_name: selenium
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
    shm_size: '2gb'
