name: Hello Python

on:
    push:
        branches: [ "main" ]

jobs:
    hello-python:
        runs-on: ubuntu-latest

        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Run script
            run: python python/hello.py