name: K8s - Deploy Supermario

on:
  workflow_dispatch:

jobs:
  build_push:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout no código
         uses: actions/checkout@v4
       
       
       - name: Login DockerHub
         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

        
       - name: Build imagem
         run: | 
           docker build -t ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:0.${{ github.run_number}} -f mariohtml5/Dockerfile mariohtml5
           docker tag ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:0.${{ github.run_number }} ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:latest
       - name: Push da imagem
         run: |
           docker push ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:0.${{ github.run_number}}
           docker push ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalando kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.3'

      - name: Configurando Kubeconfig a partir do Secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_K3S }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy Supermario
        run: |
          kubectl create deploy supermario --image=${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMAGE }}:0.${{ github.run_number}} --insecure-skip-tls-verify
          sleep 15
          kubectl get pods --insecure-skip-tls-verify