name: Trivy Scan

on:
  workflow_dispatch:
    

jobs:
  trivy-scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      
      - name: Build para trivy-scan
        run: docker build -t course-catalog:teste -f course-catalog/Dockerfile course-catalog

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: course-catalog:teste
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'